### PR TITLE
feat: add GoReleaser Azure DevOps Extension and GitHub Action to "Latest releases"

### PR DESCRIPTION
**Pull request by dirien**
add GoReleaser Azure DevOps Extension to "Latest releases"

### CODE REVIEW

**Comment by dirien** [comment]
In case you dont "scan" this repo @caarlos0 actively!

**Comment by caarlos0** [comment]
sg, lets add the action too?

**Comment by dirien** [comment]
@caarlos0 done :)

**Comment by caarlos0** [comment]
dope, thanks!

**Pull request merged**
